
KMAKE_VOLUME ?= /tmp/kmake-vol
KMAKE_OWNER ?= /tmp/kmake-owner
KMAKE_WORKDIR ?= $(CURDIR)

.PHONY: .KMAKEVOL
.KMAKEVOL: $(KMAKE_VOLUME)
	cp -rv $(KMAKE_WORKDIR) $(KMAKE_VOLUME)

.PHONY: .KMAKEINIT
.KMAKEINIT: $(KMAKE_WORKDIR)
	cp -rv $(KMAKE_VOLUME)/* $(KMAKE_WORKDIR)

.PHONY: .KMAKEOWNER
.KMAKEOWNER: $(KMAKE_WORKDIR)
	cp -v $(KMAKE_OWNER)/* $(KMAKE_WORKDIR)

$(KMAKE_VOLUME) $(KMAKE_WORKDIR):
	mkdir -p $@

.PHONY: .KMAKESLEEP
.KMAKESLEEP:
	@echo sleeping
	tail -f /dev/null

